version: '3'
services:
  myapp-main:
    image: golf-docker:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/golf_docker_2025
      #- spring.datasource.url=jdbc:mysql://s4-fall-2022.ce2vcezehro2.us-east-1.rds.amazonaws.com/fall_2022
      - spring.datasource.password=nsIHS936DMA
      - spring.datasource.username=root